name: spotsstarsandstripes.com
favicon: null
layout_spectrum: 0.7832250641658902
typography_spectrum: 0.601185193285346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5094511995557696
  lightness: 0.46217448241077363
  saturation: 0.12768069421872497
  rhythmicContrast: 0.022445987444370985
purpose: []
